[project]
name = "buhgalter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.118.3",
    "gspread-asyncio>=2.0.0",
    "loguru>=0.7.3",
    "uvicorn>=0.37.0",
]
